services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      network: host
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      network: host
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
